language: rust
services:
  - docker
before_install:
  docker run -d -v $(pwd)/examples/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg -v /tmp/socket:/var/run --entrypoint haproxy -p 9999:9999 haproxy:latest -db -f /usr/local/etc/haproxy/haproxy.cfg
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
  - cargo test --verbose --workspace -- --ignored
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID -- --include-ignored -Z unstable-options
  fi
