language: rust
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi